MODEL:
  PRETRAIN_CHOICE: 'imagenet' # imagenet, LUP
  PRETRAIN_PATH: "/data4/xxxx/checkpoint/jx_vit_base_p16_224-80ecf9dd.pth"
  METRIC_LOSS_TYPE: 'triplet_center' 
  DIM: 768
  IF_LABELSMOOTH: 'on'
  NAME: 'only_attribute_recognition' 
  NO_MARGIN: True
  DEVICE_ID: ('7')
  TRANSFORMER_TYPE: "only_attr_vit_base_patch16_224_TransReID" 
  STRIDE_SIZE: 12
  DROP_PATH: 0.1 ###### avoid overfitting
  # FREEZE_PATCH_EMBED: True
  # FIXED_RES_BN: True

INPUT:
  SIZE_TRAIN: [256,128]
  SIZE_TEST: [256,128]
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]
  REA: # random erasing
    ENABLED: True
  # LGT: # Local Grayscale Transfomation
  #   DO_LGT: True
  #   PROB: 0.5
  # CJ:
  #   ENABLED: True
  #   PROB: 1.0
  #   BRIGHTNESS: 0.15
  #   CONTRAST: 0.15
  #   SATURATION: 0.1
  #   HUE: 0.1
    
DATASETS:
  TRAIN: ('UAVHuman',)
  TEST: ('UAVHuman',)
  ROOT_DIR: ('/data4/xxxx') # root of datasets

DATALOADER:
  SAMPLER: 'softmax_triplet' # softmax_triplet, graph_sampler, single_domain, center_hard_sampler
  NUM_INSTANCE: 4
  NUM_WORKERS: 8
  CAMERA_TO_DOMAIN: True

SOLVER:
  OPTIMIZER_NAME: 'SGD' # AdamW, SAM
  MAX_EPOCHS: 20 # 60 for reid # 15 for attr_re
  BASE_LR: 0.01 # for SGD /
  IMS_PER_BATCH: 64
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 5
  LOG_PERIOD: 60 ## 60
  EVAL_PERIOD: 1
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2
  SEED: 1234
  CENTER_LOSS_WEIGHT: 0.0005

TEST:
  EVAL: True
  IMS_PER_BATCH: 256
  # RE_RANKING: True # False
  RE_RANKING: False #True # False
  QUERY_AGGREGATE: False #True
  NECK_FEAT: 'before'
  FEAT_NORM: True
  ATTRIBUTE_RECOGNITION: True

LOG_ROOT: '/data3/xxx/recurrence/' # root of log file
TB_LOG_ROOT: './tb_log/'


LOG_NAME: 'GENDER_BEST'


LOSS:
  FOCAL_LOSS: False
  LOGSOFTMAX_CENTER_LOSS: False
  ARCFACE: False
  LSOFTMAX_LOSS: True
  CENTER_LOSS_WEIGHT: 0.0005 ## just for attr center_loss
  L_MARGIN: 5 ## just for attr lsoftmax

SAVE_MODEL: [0]