MODEL:
  PRETRAIN_CHOICE: 'imagenet' # imagenet, LUP
  PRETRAIN_PATH: "/data4/xxxx/checkpoint/jx_vit_base_p16_224-80ecf9dd.pth"
  METRIC_LOSS_TYPE: 'triplet_center' # triplet, triplet_center
  # DIM: 1024 # current model dim
  DIM: 768
  # DIM: 1024
  IF_LABELSMOOTH: 'on'
  NAME: 'only_attribute_recognition' #'attr_vit' 
  NO_MARGIN: True
  DEVICE_ID: ('7')
  TRANSFORMER_TYPE: "only_attr_vit_base_patch16_224_TransReID" # 
  STRIDE_SIZE: 12
  DROP_PATH: 0.1 ###### avoid overfitting
  # FREEZE_PATCH_EMBED: True
  # FIXED_RES_BN: True

INPUT:
  SIZE_TRAIN: [256,128]
  SIZE_TEST: [256,128]
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]
 

DATASETS:
  TRAIN: ('UAVHuman',)
  TEST: ('UAVHuman',)
  ROOT_DIR: ('/data4/xxxx') # root of datasets

DATALOADER:
  SAMPLER: 'softmax_triplet' # softmax_triplet, graph_sampler, single_domain, center_hard_sampler
  NUM_INSTANCE: 4
  NUM_WORKERS: 8
  CAMERA_TO_DOMAIN: True

SOLVER:
  OPTIMIZER_NAME: 'AdamW' # AdamW, SAM
  MAX_EPOCHS: 20 # 60 for reid # 15 for attr_re
  BASE_LR: 0.000035 # for AdamW
  IMS_PER_BATCH: 64
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 5
  LOG_PERIOD: 60 ## 60
  EVAL_PERIOD: 1
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2
  SEED: 1234
  CENTER_LOSS_WEIGHT: 0.0005

TEST:
  EVAL: True
  IMS_PER_BATCH: 256
  # RE_RANKING: True # False
  RE_RANKING: False #True # False
  QUERY_AGGREGATE: False #True
 


  NECK_FEAT: 'before'
  FEAT_NORM: True
  ATTRIBUTE_RECOGNITION: True

LOG_ROOT: '/data3/xxxx/recurrence/' # root of log file
TB_LOG_ROOT: './tb_log/'



LOG_NAME: 'BACKPACK_BEST'

# 

LOSS:
  FOCAL_LOSS: False
  LOGSOFTMAX_CENTER_LOSS: False
  LOGSOFTMAX_CENTER_LOSS_ATTR: False
  ARCFACE: False
  LSOFTMAX_LOSS: False
  CENTER_LOSS_WEIGHT: 0.0005 ## just for attr center_loss
  L_MARGIN: 5 ## just for attr lsoftmax

SAVE_MODEL: [1]